name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config directory and files
        run: |
          mkdir -p config
          
          # Create Google Maps config
          cat > config/google-maps.json << 'EOF'
          ${{ secrets.GOOGLE_MAPS_CONFIG || '{"apiKey":null,"mapOptions":{"zoom":16}}' }}
          EOF
          
          # Create EmailJS config
          cat > config/emailjs.json << 'EOF'
          ${{ secrets.EMAILJS_CONFIG || '{"publicKey":null,"serviceId":null,"templateId":null}' }}
          EOF
          
          # Create Site config
          cat > config/site-config.json << 'EOF'
          ${{ secrets.SITE_CONFIG || '{"company":{"name":"(주)그린테크"},"contact":{"email":"jalhanda88@gmail.com"}}' }}
          EOF
          
          # Debug: Check if files were created
          echo "=== Config files created ==="
          ls -la config/
          echo "=== Checking file contents ==="
          head -n 5 config/*.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4