name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create config files
        run: |
          mkdir -p config
          echo '${{ secrets.GOOGLE_MAPS_CONFIG }}' > config/google-maps.json
          echo '${{ secrets.EMAILJS_CONFIG }}' > config/emailjs.json
          echo '${{ secrets.SITE_CONFIG }}' > config/site-config.json
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./